//
// Generated file, do not edit! Created by opp_msgc 4.5 from Job.msg.
//

#ifndef _JOB_M_H_
#define _JOB_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Job.msg</tt> by opp_msgc.
 * <pre>
 * message Job {
 *     double iat;
 * 	double departureTime;
 * 	int ID;
 * }
 * </pre>
 */
class Job : public ::cMessage
{
  protected:
    double iat_var;
    double departureTime_var;
    int ID_var;

  private:
    void copy(const Job& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Job&);

  public:
    Job(const char *name=NULL, int kind=0);
    Job(const Job& other);
    virtual ~Job();
    Job& operator=(const Job& other);
    virtual Job *dup() const {return new Job(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getIat() const;
    virtual void setIat(double iat);
    virtual double getDepartureTime() const;
    virtual void setDepartureTime(double departureTime);
    virtual int getID() const;
    virtual void setID(int ID);
};

inline void doPacking(cCommBuffer *b, Job& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Job& obj) {obj.parsimUnpack(b);}


#endif // _JOB_M_H_
